version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Run tests
          command: |
            python run_tests.py
