databases:
  - name: resulttracker
    databaseName: mitplayers
    user: postgres

services:
  - type: web
    name: resulttracker
    runtime: python
    buildCommand: "./build.bat" # Adjust the build command for Windows
    startCommand: "gunicorn resulttracker.wsgi:base"
    envVars:
      - key: DATABASE_URL
        value: "postgres://postgres:Shrish05!@database-1.cpaiqu42o66b.us-west-1.rds.amazonaws.com:5432/mitplayers"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
